### ISSUE TITLE
Mixing % and px columns in table layout

### ISSUE THREAD

**Issue by miyconst** [Juicy/juicy-tile-table#8]
The setup I am trying to achieve: multiple tiles per row with static width regardless of screen width.

![image](https://cloud.githubusercontent.com/assets/6435556/14289887/1d5de8c0-fb5d-11e5-9e50-4f730b966eeb.png)

Right now `juicy-tile-table` does not support mix of `%` and `px` columns in a table, that is why all columns get width in `%`. This causes empty space per each tile as soon as screen gets wider than first break point value.

![image](https://cloud.githubusercontent.com/assets/6435556/14290088/f22c2288-fb5d-11e5-9f1b-5067981ab31f.png)

This gets better when the tiles packed inside a group:

![image](https://cloud.githubusercontent.com/assets/6435556/14290164/41019b2c-fb5e-11e5-8033-468408ab1096.png)

But the last empty space column is still defined in `%`, and the value is calculated as if the table would be same size as first break point.

![image](https://cloud.githubusercontent.com/assets/6435556/14290239/8ce28c7c-fb5e-11e5-866b-0c3fe018563d.png)

As soon as screen width exceed first break point value, `38.9%` no longer occupies entire empty space, and the extra space is split among all the columns.

The issue can be solved by replacing `38.9%` with `100%`. It acts like "100%" of the rest space. Creating multiple columns with `%` width also acts correctly, it splits the available space.

I will create a jsfiddle to demonstrate the behavior.

cc @tomalec, @warpech, @Starcounter-Jack

**Comment by miyconst** [comment]
This jsfiddle demonstrates what I meant:
https://jsfiddle.net/szaz5wow/

![image](https://cloud.githubusercontent.com/assets/6435556/14297995/bd058c78-fb82-11e5-90b9-aad5dd0cf326.png)

**Comment by tomalec** [comment]
I'd like to note, that it should work fine with `juicy-tile-grid`. (Safari Tech Preview get CSS Grid support, so after adapting few `-webkit` prefixes it should works there)

Such solution makes it impossible to specify that given track or item should take 50% of parent size, and adapt to its changes. What would probably be more common case. If I recall correctly we agreed some time ago, that we would like to encourage people to use `%` and flexible size rather than fixed sizes.

CSS Table Layout spec does not use free space, that's why I'm a bit afraid, that it's a very specific case that makes proposed solution work here. But for sure it's worth investigating.

Also, the way I proposed https://github.com/Starcounter/RebelsLounge/issues/21 and some meetings after: "Let the editor/designer use more grid-related more CSS-like properties, not just out magical, enigmatic, per-tile properties", should help us solve and avoid such problems.
